// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetClientID() {
  return window['go']['main']['App']['GetClientID']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
